module.exports = {
  AuthenticationRoutes: require("./AuthenticationRoutes").default,
  AgentRoutes: require("./AgentRoutes").default,
  UserRoutes: require("./UserRoutes"),
  CategoryRoutes: require("./CategoryRoutes"),
  ServiceRoutes: require("./ServiceRoutes"),
  RequestRoutes: require("./RequestRoutes"),
  BookingRoutes: require("./BookingRoutes"),
  ServiceRatingRoutes: require("./ServiceRatingRoutes"),
  AdminRoutes: require("./AdminRoutes").default,
  SendRoutes: require("./SendRoutes"),
  OfferingRoutes: require("./OfferingRoutes"),
  FileRoutes: require("./FileRoutes").default,
  ScheduleRoutes: require("./ScheduleRoutes"),
  ChatRoutes: require("./ChatRoutes"),
};
