module.exports = {
  CognitoService: require("./CognitoService"),
  AgentService: require("./AgentService"),
  AgentPrivateService: require("./AgentPrivateService"),
  UserService: require("./UserService"),
  UserPrivateService: require("./UserPrivateService"),
  JwtService: require("./JwtService"),
  CategoryService: require("./CategoryService"),
  ServiceService: require("./ServiceService"),
  BookingService: require("./BookingService"),
  RequestService: require("./RequestService"),
  ServiceRatingService: require("./ServiceRatingService"),
  ProductService: require("./ProductService"),
  FileService: require("./FileService"),
  ScheduleService: require("./ScheduleService"),
  ChatService: require("./ChatService"),
};
