module.exports = {
  UserManager: require("./UserManager"),
  AuthenticationManager: require("./AuthenticationManager"),
  RequestManager: require("./RequestManager"),
  BookingManager: require("./BookingManager"),
  AgentManager: require("./AgentManager"),
  CategoryManager: require("./CategoryManager"),
  ServiceManager: require("./OfferingManager"),
  ServiceRatingManager: require("./ServiceRatingManager"),
  SendManager: require("./SendManager"),
  OfferingManager: require("./OfferingManager"),
  FileManager: require("./FileManager"),
  ScheduleManager: require("./ScheduleManager"),
  ChatManager: require("./ChatManager"),
};
